### ISSUE TITLE
AttributeError: Can't pickle local object 'ArgumentParser.__init__.<locals>.identity'

### ISSUE THREAD

**Issue by upendrak** [ratschlab/spladder#79] opened 2019-03-19 17:23 UTC
* spladder version: 2.0.0
* Python version: 3.6.7
* Operating System: Ubuntu 18.04

### Description

@akahles thanks for helping me figure out the issue with `spladder build` command. The `spladder build` worked perfectly fine and generated all the output files but when I ran the `spladder test` command, I get the below error. Any thoughts of why this would happen?

### What I Did

```
spladder test -a TCS10-1-A7_trimmed.sorted.bam,TCS10-2-A8_trimmed.sorted.bam -b THS10-1-A10_trimmed.sorted.bam,THS10-2-A11_trimmed.sorted.bam -o spladder_build --parallel 6
Capped 2633/114352 outlier expression counts (2.30 percent)
Traceback (most recent call last):
  File "/usr/local/bin/spladder", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/spladder/spladder.py", line 182, in main
    options.func(options)
  File "/usr/local/lib/python3.6/dist-packages/spladder/spladder_test.py", line 764, in spladder_test
    (pvals, cov_used, disp_raw_used, disp_adj_used) = run_testing(cov, dmatrix0, dmatrix1, sf, options, event_type, test_idx)
  File "/usr/local/lib/python3.6/dist-packages/spladder/spladder_test.py", line 523, in run_testing
    (disp_raw, disp_raw_conv) = estimate_dispersion(cov, dmatrix1, sf, options, test_idx, event_type)
  File "/usr/local/lib/python3.6/dist-packages/spladder/spladder_test.py", line 194, in estimate_dispersion
    tmp = result.pop(0).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 670, in get
    raise self._value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 450, in _handle_tasks
    put(task)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
AttributeError: Can't pickle local object 'ArgumentParser.__init__.<locals>.identity'
```

**Comment by akahles** [comment] 2019-03-19 21:27
Thank you for reporting. I am working on a new release fixing this bug. I will make it available in the next day or two. You can already try it out using the development branch of the repository.

Best,
Andre

**Comment by upendrak** [comment] 2019-03-20 22:45
@akahles I get the same error with the development branch as well with the same command. I am happy to share the files with you if you want to look at them.

Thanks,
Upendra

**Comment by akahles** [comment] 2019-03-21 13:43
Dear Upendra,
Thanks for trying. I would be glad if you could share the files with me, so it is easier for me to reproduce the error.
Best,
Andre

**Comment by upendrak** [comment] 2019-03-21 19:36
Hi @akahles,

Here is the [link](https://de.cyverse.org/dl/d/3B56DB2D-5132-48E7-B274-757551675C54/spladder_data.tar.gz) to the input data that I was using with spladder-2.0.0. You can use `wget` or `curl` to download it. 

Thanks, and please let me know if you need any further details about the data.

**Comment by akahles** [comment] 2019-03-24 21:07
Thank you very much again for sending the data. Unfortunately, I am still unable to reproduce your error. On my end SplAdder runs through with your data. I have just released the latest version (2.0.1, fixing another issue). Could you please uninstall the older version and try this new release?

**Comment by upendrak** [comment] 2019-03-25 22:11
Hi, @akahles thanks for checking my data. I will go ahead and test the new version and I hope it will work as you have noticed. Will get back to you soon. Thanks again

**Comment by upendrak** [comment] 2019-03-27 16:56
Hi @akahles it worked but I need help with the visualization step though. I ask this because I didn't see the wiki page for the new version, the wiki page still points to the old version. Anyway when I run the viz step, I get this error..

```
spladder viz -o spladder_build -b TCS10-1-A7_trimmed.sorted.bam,TCS10-2-A8_trimmed.sorted.bam,THS10-1-A10_trimmed.sorted.bam,THS10-2-A11_trimmed.sorted.bam -L WT1,WT2,MT1,MT2 -g "FvH4_c10g00030"
```

```
Traceback (most recent call last):
  File "/usr/local/bin/spladder", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/spladder/spladder.py", line 190, in main
    options.func(options)
  File "/usr/local/lib/python3.6/dist-packages/spladder/spladder_viz.py", line 43, in spladder_viz
    options = settings.parse_args(options, identity='viz')
  File "/usr/local/lib/python3.6/dist-packages/spladder/settings.py", line 203, in parse_args
    if not os.path.isfile(fname):
  File "/usr/lib/python3.6/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not list
```

Can you please let me know how do I fix this problem?

**Comment by akahles** [comment] 2019-03-29 12:07
Hi @upendrak , glad it is working now. I would like to close this issue here. Your last post seems to indicate a new problem. Would you mind opening a new issue for that? 
Thanks,
Andre

**Closed by akahles** 2019-03-29 12:07 UTC
