### ISSUE TITLE
spladder_test.py -t intron_retention fails with index out of range error

### ISSUE THREAD

**Issue by rschulzUK** [ratschlab/spladder#31] opened 2016-05-04 15:27 UTC
Hi Andre,

spladder_test fails for the intron_retention category of alt splicing events with an index out of range error (see below). All other categories work fine, except mutex_exon. However, mutex_exon fails with a different error, shown at the bottom. Have attached the contents of `./output_9_fwd` (spladder output directory). As always, any help getting over this bump in the road is much appreciated.

Best, Reiner
[output_9_fwd.zip](https://github.com/ratschlab/spladder/files/249049/output_9_fwd.zip)

intron_retention error:
```
$ python ~/bin/spladder-master/python/spladder_test.py -o ./output_9_fwd -a A.fwd.9,B.fwd.9 -b E.fwd.9,F.fwd.9 -n 100 -c 2 -v y -t intron_retention
Loading expression counts from ./output_9_fwd/spladder/genes_graph_conf2.merge_graphs.gene_exp.hdf5
Estimating size factors
Testing intron_retention events
Collecting intron confirmation values
Constructing event IDs
Traceback (most recent call last):
  File "/home/rschulz/bin/spladder-master/python/spladder_test.py", line 873, in <module>
    main()
  File "/home/rschulz/bin/spladder-master/python/spladder_test.py", line 787, in main
    (cov, gene_idx, event_idx, event_ids, event_strains) = quantify.quantify_from_counted_events(CFG['fname_events'], sp.r_[idx1, idx2], event_type, CFG)
  File "/home/rschulz/bin/spladder-master/python/modules/alt_splice/quantify.py", line 516, in quantify_from_counted_events
    event_ids = get_event_ids(IN, event_type, event_idx, CFG)
  File "/home/rschulz/bin/spladder-master/python/modules/alt_splice/quantify.py", line 677, in get_event_ids
    event_ids0 = sp.array(['%s:%s' % (gene_chr[i], '-'.join(IN['event_pos'][i, [1, 2]].astype('str'))) for i in event_idx], dtype='str')
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (-------src-dir-------/h5py/_objects.c:2582)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (-------src-dir-------/h5py/_objects.c:2541)
  File "/home/rschulz/anaconda/lib/python2.7/site-packages/h5py/_hl/dataset.py", line 462, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/home/rschulz/anaconda/lib/python2.7/site-packages/h5py/_hl/selections.py", line 88, in select
    sel[args]
  File "/home/rschulz/anaconda/lib/python2.7/site-packages/h5py/_hl/selections.py", line 382, in __getitem__
    start, count, step, scalar = _handle_simple(self.shape, vector)
  File "/home/rschulz/anaconda/lib/python2.7/site-packages/h5py/_hl/selections.py", line 447, in _handle_simple
    x,y,z = _translate_int(int(arg), length)
  File "/home/rschulz/anaconda/lib/python2.7/site-packages/h5py/_hl/selections.py", line 467, in _translate_int
    raise ValueError("Index (%s) out of range (0-%s)" % (exp, length-1))
ValueError: Index (2) out of range (0-1)
```

mutex_exon error:
```
$ python ~/bin/spladder-master/python/spladder_test.py -o ./output_9_fwd -a A.fwd.9,B.fwd.9 -b E.fwd.9,F.fwd.9 -n 100 -c 2 -v y -t mutex_exons
Loading expression counts from ./output_9_fwd/spladder/genes_graph_conf2.merge_graphs.gene_exp.hdf5
Estimating size factors
Testing mutex_exons events
Collecting intron confirmation values
Constructing event IDs
Traceback (most recent call last):
  File "/home/rschulz/bin/spladder-master/python/spladder_test.py", line 873, in <module>
    main()
  File "/home/rschulz/bin/spladder-master/python/spladder_test.py", line 787, in main
    (cov, gene_idx, event_idx, event_ids, event_strains) = quantify.quantify_from_counted_events(CFG['fname_events'], sp.r_[idx1, idx2], event_type, CFG)
  File "/home/rschulz/bin/spladder-master/python/modules/alt_splice/quantify.py", line 516, in quantify_from_counted_events
    event_ids = get_event_ids(IN, event_type, event_idx, CFG)
  File "/home/rschulz/bin/spladder-master/python/modules/alt_splice/quantify.py", line 683, in get_event_ids
    event_ids0 = sp.array(['%s:%s' % (gene_chr[i], '-'.join(IN['event_pos'][i, :4].astype('str'))) for i in event_idx], dtype='str')
TypeError: sequence item 0: expected string, numpy.ndarray found
```

**Comment by akahles** [comment] 2016-05-05 19:40
Hi Reiner,
The issue seems to be upstream of the testing. What annotation file are you using as input to SplAdder? I am trying to reproduce some upstream calls.

Thanks and Cheers,
Andre

**Comment by rschulzUK** [comment] 2016-05-06 06:16
Hi Andre,

Thanks for looking into this. I attach the GFF and pickle files for the annotation of mouse Chr 9, forward strand.

Best, r
[gencode.vM9.annotation.9.fwd.gff3.zip](https://github.com/ratschlab/spladder/files/251598/gencode.vM9.annotation.9.fwd.gff3.zip)

**Comment by akahles** [comment] 2016-05-06 15:17
Hi Reiner, 
Thank you for providing additional information. I have pushed a couple of fixes to the development branch. Could you please try, whether this resolves the issue?
Thanks, Andre

**Comment by akahles** [comment] 2016-05-06 15:18
I forgot to mention. When trying out the new code, could you please remove the file "merge_graphs_intron_retention_C2.counts.hdf5" from your output directory and rerun spladder.py with the same settings as before? A correct version of the hdf5 will be generated, so the testing code can use it.

**Comment by rschulzUK** [comment] 2016-05-06 19:23
Hi Andre,

Reran intron_retention after removal of above file: no errors.
Reran mutex_exons: no errors.

Cheers, r

**Comment by akahles** [comment] 2016-05-06 19:25
Thanks for reporting back. Will close this for now. Please re-open or create new issue, in case the same problem appears again.

**Closed by akahles** 2016-05-06 19:25 UTC
