### ISSUE TITLE
Differential expression @ isoform level

### ISSUE THREAD

**Issue by hasantos** [ratschlab/spladder#8] opened 2015-05-19 11:49 UTC
Dear Andre,

How are you? Thanks for developing this tool, it looks quite promising.
I am trying to run spladder on some Drosophila melanogaster samples to infer about differential expression at the isoform level - i.e. to infer if there are any splicing event switching between conditions (for example, wt and knockout of some protein).
Up until now, I had some problems:

1) I can't find any merge_graphs_*_C3.confirmed.txt files to be created which is indicative of not being able to find significant splicing events (?)
2) I did tried to run this on some human samples that we have in the lab, and for some of the analyzed genes I've obtained the aforementioned files and all of the .pdf files that were being produced had the splicing schemes (I mean the lines connecting exons in a diagram sort of way)
3) I'm not sure how to implement rdiff to do the differential expression analysis neither how to use the *pickle files

Could you please clarify me on this?

Thank you. 

Best,
Hugo

**Comment by warrenmcg** [comment] 2015-08-30 18:59
Hi Hugo,

André is going to be releasing a script that uses rDiff to analyze the data soon, so if you can wait, look out for that update.

Otherwise, he recommended that you use the GFF3 files that annotate the splicing events you wish to test (if you need help concatenating them together, simply do `cat *.gff3 > allEvents.gff3`, and then do the code detailed [here](http://stackoverflow.com/a/20639730) to remove the extra header lines). You then submit this as the annotation file for rDiff (the `-g` flag). You can find rDiff [here](https://github.com/ratschlab/rDiff). This will repeat the process of counting the coverage across the events, but it implements the correct statistical tests, and is equivalent to the script that André will be releasing soon.

As for the first issue with your Drosophila files, what is the command you submit to spladder.py?

**Comment by akahles** [comment] 2015-08-30 23:21
Hi Warren and Hugo,
Thanks for jumping in @warrenmcg . (And apologies to @hasantos for letting this issue sit here for so long.) The wiki description is still in the works and mainly on hold while I am working on the testing framework integrated into SplAdder.

To answer Hugo's questions:
1) If no *.confirmed.txt files are created this means that none of the detected alternative splicing events was sufficiently supported by RNA-Seq reads in the data. 
2) not quite sure what the question is.
3) As detailed in Warren's previous post, the testing is currently done by using the *.gff files as input for rDiff.

I will post here as soon as there is any news regarding the SplAdder testing. Thank you for your patience.

Best Andre.

**Comment by ajw2329** [comment] 2016-07-12 22:33
Hello,

Thanks also for writing such a great tool.  I recently started using it and it is fantastic!

I am also interested in differential splicing analysis - in the SplAdder manuscript you mention an alternative SplAdder + GLM approach that outperforms the SplAdder + rDiff combination in a number of respects.  Is an implementation of the GLM approach likely to be released anytime soon?

Thanks again,
Andrew

**Comment by warrenmcg** [comment] 2016-07-13 04:00
Hi Andrew,

The testing module for SplAdder incorporates the GLM approach. Use the "spladder_test.py" script. If you run "python /path/to/spladder/python/spladder_test.py -h" it will run through the options that need to be set. Post back to the thread or start a new issue if you have questions.

Best,
Warren

**Comment by ajw2329** [comment] 2016-07-15 00:41
Thanks very much Warren!  It is working great aside from some issues with intron retention.  I will start a new issue once I've played with it some more.  

Best,
Andrew

**Comment by asgarhussain** [comment] 2016-10-20 06:47
Hi Andre
I am having following problem while running spladder_test.py:

File "/home/asgar.hussain/scratch/tools/spladder-master/python/spladder_test.py", line 873, in <module>
    main()
  File "/home/asgar.hussain/scratch/tools/spladder-master/python/spladder_test.py", line 757, in main
    gene_counts, gene_strains, gene_ids = get_gene_expression(CFG, fn_out=CFG['fname_exp_hdf5'], strain_subset=condition_strains)
  File "/home/asgar.hussain/scratch/tools/spladder-master/python/spladder_test.py", line 107, in get_gene_expression
    genes = cPickle.load(open(CFG['fname_genes'], 'r'))[0]
IOError: [Errno 2] No such file or directory: 'tmp/spladder/genes_graph_conf3.merge_graphs.pickle'

Please tell me. How to fix this

Best,
Asgar Hussain

**Comment by akahles** [comment] 2016-10-20 15:50
Hi Asgar,
does a file `tmp/spladder/genes_graph_conf3.merge_graphs.hdf5` exist?
Cheers,
Andre

**Comment by Trandamere** [comment] 2017-01-09 01:53
Hi Andre
I also having following problem while running spladder_test.py:
python spladder_test.py -o /home/luping/spladder-master/spladder-GLM/ -a /home/luping/spladder-master/spladderesult-new-gtf/spladder/genes_graph_conf3.Coni_1.pickle -b /home/luping/spladder-master/spladderesult-new-gtf/spladder/genes_graph_conf3.Ger12h_1.pickle 
Traceback (most recent call last):
  File "spladder_test.py", line 873, in <module>
    main()
  File "spladder_test.py", line 757, in main
    gene_counts, gene_strains, gene_ids = get_gene_expression(CFG, fn_out=CFG['fname_exp_hdf5'], strain_subset=condition_strains)
  File "spladder_test.py", line 107, in get_gene_expression
    genes = cPickle.load(open(CFG['fname_genes'], 'r'))[0]
IOError: [Errno 2] No such file or directory: '/home/luping/spladder-master/spladder-GLM/spladder/genes_graph_conf3.merge_graphs.pickle'

then i copy the file genes_graph_conf3.merge_graphs.count.hdf5 and genes_graph_conf3.merge_graphs.pickle into the /home/luping/spladder-master/spladder-GLM/spladder/
but it have another error,like this:
Traceback (most recent call last):
  File "spladder_test.py", line 873, in <module>
    main()
  File "spladder_test.py", line 787, in main
    (cov, gene_idx, event_idx, event_ids, event_strains) = quantify.quantify_from_counted_events(CFG['fname_events'], sp.r_[idx1, idx2], event_type, CFG)
  File "/home/luping/spladder-master/python/modules/alt_splice/quantify.py", line 388, in quantify_from_counted_events
    IN = h5py.File(event_fn, 'r', driver='core')
  File "/home/luping/sf/python/lib/python2.7/site-packages/h5py/_hl/files.py", line 272, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/luping/sf/python/lib/python2.7/site-packages/h5py/_hl/files.py", line 92, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-3TLvcq-build/h5py/_objects.c:2684)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-3TLvcq-build/h5py/_objects.c:2642)
  File "h5py/h5f.pyx", line 76, in h5py.h5f.open (/tmp/pip-3TLvcq-build/h5py/h5f.c:1930)
IOError: Unable to open file (Unable to open file)

Please tell me. How to fix this

Best,
Tyrndamere

**Comment by akahles** [comment] 2017-01-09 11:12
Hi Tyrndamere,

The testing script is not invoked with the pickle files but with the bam files of the samples you would like to test. So if you have run spladder on samples A1.bam, A2.bam, B1.bam and B2.bam, then the test would be called as:
```
python spladder_test.py -o OUTDIR -a A1.bam,A2.bam -b B1.bam,B2.bam
```

Please let me know whether this fixes your problem.

Best,
Andre

**Comment by Trandamere** [comment] 2017-01-09 12:31
Hi Andre,
I fix my command like this;
python spladder_test.py -o /home/spladder-master/spladder-GLM/ -a /disk/bam/Coni_1.bam,/disk/bam/Coni_2.bam,/disk/bam/Coni_3.bam -b /disk/bam/Ger12h_1.bam,/disk/bam/Ger12h_2.bam,/disk/bam/Ger12h_3.bam --parallel=10
Traceback (most recent call last):
  File "spladder_test.py", line 873, in <module>
    main()
  File "spladder_test.py", line 757, in main
    gene_counts, gene_strains, gene_ids = get_gene_expression(CFG, fn_out=CFG['fname_exp_hdf5'], strain_subset=condition_strains)
  File "spladder_test.py", line 107, in get_gene_expression
    genes = cPickle.load(open(CFG['fname_genes'], 'r'))[0]
IOError: [Errno 2] No such file or directory: '/home/spladder-master/spladder-GLM/spladder/genes_graph_conf3.merge_graphs.pickle'



then I cpoy the file genes_graph_conf3.merge_graphs.count.hdf5 and genes_graph_conf3.merge_graphs into /home/spladder-master/spladder-GLM/spladder/    run it again  then I get another error like this
Traceback (most recent call last):
  File "spladder_test.py", line 873, in <module>
    main()
  File "spladder_test.py", line 787, in main
    (cov, gene_idx, event_idx, event_ids, event_strains) = quantify.quantify_from_counted_events(CFG['fname_events'], sp.r_[idx1, idx2], event_type, CFG)
  File "/home/spladder-master/python/modules/alt_splice/quantify.py", line 388, in quantify_from_counted_events
    IN = h5py.File(event_fn, 'r', driver='core')
  File "/home/sf/python/lib/python2.7/site-packages/h5py/_hl/files.py", line 272, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/sf/python/lib/python2.7/site-packages/h5py/_hl/files.py", line 92, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-3TLvcq-build/h5py/_objects.c:2684)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-3TLvcq-build/h5py/_objects.c:2642)
  File "h5py/h5f.pyx", line 76, in h5py.h5f.open (/tmp/pip-3TLvcq-build/h5py/h5f.c:1930)
IOError: Unable to open file (Unable to open file)
Please tell me. How to fix this

Best,
Tyrndamere

**Comment by akahles** [comment] 2017-01-09 21:06
Can you please send me your original spladder call? The starting with `python spladder.py ...`

**Comment by Trandamere** [comment] 2017-01-10 01:17
my original spladder call like this
python spladder.py -a /disk/bam/gtf/merged.gtf -o /home/spladder-master/spladderesult-new-gtf -b /disk/bam/Coni_1.bam,/disk/bam/Ger12h_1.bam,/disk/bam/Hy24h_1.bam,/disk/bam/Inf3d_1.bam,/disk/bam/NH4NO3_1.bam,/dis/bam/Sex3d_1.bam,/disk/bam/Sex8d-1.bam,/disk/bam/Sex10d_1.bam

Conditions must be the same as the spladder_test?

**Comment by akahles** [comment] 2017-01-10 11:16
The spladder test script automatically searches for data in the spladder output directory. You therefor need to provide the same output directory. Spladder will automatically create sub-directories for you tests. Your call should be:
```
python spladder_test.py -o /home/spladder-master/spladderesult-new-gtf -a /disk/bam/Coni_1.bam,/disk/bam/Coni_2.bam,/disk/bam/Coni_3.bam -b /disk/bam/Ger12h_1.bam,/disk/bam/Ger12h_2.bam,/disk/bam/Ger12h_3.bam --parallel=10
```

**Comment by Trandamere** [comment] 2017-01-11 06:21
Hi Andre,
I  provide the same output directory for spladder test then I get a ValueError like this:
All events of type exon_skip were filtered out due to low coverage. Please try re-running with less stringent filter criteria
Traceback (most recent call last):
  File "spladder_test.py", line 873, in <module>
    main()
  File "spladder_test.py", line 787, in main
    (cov, gene_idx, event_idx, event_ids, event_strains) = quantify.quantify_from_counted_events(CFG['fname_events'], sp.r_[idx1, idx2], event_type, CFG)
  File "/home/luping/spladder-master/python/modules/alt_splice/quantify.py", line 516, in quantify_from_counted_events
    event_ids = get_event_ids(IN, event_type, event_idx, CFG)
  File "/home/luping/spladder-master/python/modules/alt_splice/quantify.py", line 677, in get_event_ids
    event_ids0 = sp.array(['%s:%s' % (gene_chr[i], '-'.join(IN['event_pos'][i, [1, 2]].astype('str'))) for i in event_idx], dtype='str')
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-3TLvcq-build/h5py/_objects.c:2684)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-3TLvcq-build/h5py/_objects.c:2642)
  File "/home/luping/sf/python/lib/python2.7/site-packages/h5py/_hl/dataset.py", line 462, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/home/luping/sf/python/lib/python2.7/site-packages/h5py/_hl/selections.py", line 88, in select
    sel[args]
  File "/home/luping/sf/python/lib/python2.7/site-packages/h5py/_hl/selections.py", line 382, in __getitem__
    start, count, step, scalar = _handle_simple(self.shape, vector)
  File "/home/luping/sf/python/lib/python2.7/site-packages/h5py/_hl/selections.py", line 447, in _handle_simple
    x,y,z = _translate_int(int(arg), length)
  File "/home/luping/sf/python/lib/python2.7/site-packages/h5py/_hl/selections.py", line 467, in _translate_int
    raise ValueError("Index (%s) out of range (0-%s)" % (exp, length-1))
ValueError: Index (2) out of range (0-1)

**Comment by akahles** [comment] 2018-06-19 14:53
There are multiple issues in this thread. Will close. Please re-open if still relevant.

**Closed by akahles** 2018-06-19 14:53 UTC
