### ISSUE TITLE
splADDER KeyError: 'gene_id'

### ISSUE THREAD

**Issue by rvilloutreix** [ratschlab/spladder#154] opened 2022-02-03 15:56 UTC
* spladder version: installed with pip a couple of days ago
* Python version: Python 2.7.5
* Operating System: CentOS Linux release 7.9.2009 (Core)

### Description

Hello  Andre,

I want to use splADDER to look for splice variants potentially associated with body colouration in a species of stick insects. When I try to run splADDER for splice variant detection I get an error. I converted a gff3 annotation file to a gtf one with gffread.

Thanks for you help!

### What I Did 

[***@***:Tchumash]$ spladder build -b bams/19_0340.bam -a timema_cristinae_1.3c2_braker_interproscan_predgene_and_funcann.flipped.wseq.gtf -o test/
WARNING: timema_cristinae_1.3c2_braker_interproscan_predgene_and_funcann.flipped.wseq.gtf does not have gene level information for transcript g10481.t1 - information has been inferred from tags
Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u6032583/.local/bin/spladder", line 8, in <module>
    sys.exit(main())
  File "/uufs/chpc.utah.edu/common/home/u6032583/.local/lib/python3.7/site-packages/spladder/spladder.py", line 229, in main
    options.func(options)
  File "/uufs/chpc.utah.edu/common/home/u6032583/.local/lib/python3.7/site-packages/spladder/spladder_build.py", line 63, in spladder
    options = prep_annotation(options)
  File "/uufs/chpc.utah.edu/common/home/u6032583/.local/lib/python3.7/site-packages/spladder/spladder_prep.py", line 24, in prep_annotation
    (genes, options) = init.init_genes_gtf(options)
  File "/uufs/chpc.utah.edu/common/home/u6032583/.local/lib/python3.7/site-packages/spladder/init.py", line 111, in init_genes_gtf
    gene_id = tags['gene_id']
KeyError: 'gene_id'

**Comment by akahles** [comment] 2022-02-03 16:03
Dear @rvilloutreix ,

Thank you for trying out SplAdder. Would you be able to send me the gtf file you are using? 

Unrelated to the issue you are posting, I see that you are still using Python 2.7. I would recommend to change to Python 3, as this will also make any SplAdder runs more robust.

Best,
Andre

**Comment by rvilloutreix** [comment] 2022-02-03 16:12
Dear Andre,

Thanks for your swift answer. Well noted, I'll load the module on the
cluster I am using.

Here
<https://drive.google.com/file/d/1COTDjTMyu2WgLbpLu2Sb3YC8BTYN3r-S/view?usp=sharing>
are all the files I used to run the analysis. I tried to upload them with
my issue but it failed.

Many thanks for your help,

Romain


 error-splADDER.zip
<https://drive.google.com/file/d/1COTDjTMyu2WgLbpLu2Sb3YC8BTYN3r-S/view?usp=drive_web>


Le jeu. 3 févr. 2022 à 17:03, Andre Kahles ***@***.***> a
écrit :

**Comment by akahles** [comment] 2022-02-04 09:10
Dear Romain,

Thanks a lot for sending along the files. There are several issues with the annotation files. The gtf file you have sent has some entries that miss information, so it is impossible to derive the parents of some of the elements. So I assume this is an issue with the software generating the gtf file.

I also had a look at the gff3 file, which I assume is the original one that was derived from AUGUSTUS. Here the issue is two-fold. First, it contains a fasta block, which SplAdder can not handle. I have added a rule now to ignore any further lines, if a fasta section is found. For now, you can just take the head of your file to work with (`head -n 663021 timema_cristinae_1.3c2_braker_interproscan_predgene_and_funcann.flipped.wseq.gff3`). The second issue is at least one malformed line in the gff3 file. There is a leading space in the field name for ID:
```'lg8_ord13_scaf2963\tAUGUSTUS\texon\t4296\t4757\t.\t-\t.\t ID=g4750.t1.exon1;Parent=g4750.t1;\n'```. I have added a rule to SplAdder now to chop this off, if it occurs. For you to proceed, a simple `sed -e "s/ ID/ID/g" timema_cristinae_1.3c2_braker_interproscan_predgene_and_funcann.flipped.wseq.gff3` should do the trick.
I will modify SplAdder, such that files like the above should work out of the box in the future.

Lastly, when looking at your bam files, I see that you aligned using STAR. For appropriate recognition of mismatches in the reads for filtering, you need to add `--set-mm-tag nM` to your spladder call.

Cheers,

Andre

**Comment by rvilloutreix** [comment] 2022-02-04 09:18
Dear Andre,

Many thanks for your swift answer.

Indeed, the gff3 file was generated with braker (a suite using augustus for
structural annotation).

I indeed used STAR to align my RNASeq reads to the reference genome.

Thanks for all the suggestions, I'll try them right now.

Cheers,

Romain

Le ven. 4 févr. 2022 à 10:10, Andre Kahles ***@***.***> a
écrit :

**Comment by rvilloutreix** [comment] 2022-02-11 15:00
Dear Andre,

Sorry for the late answer. Your suggestions are working, I am currently
running a test analysis.

Many thanks for your help,

Romain

**Comment by akahles** [comment] 2022-02-11 20:46
Hi Romain,

glad to hear it worked. Will close this for now. Please open a new issue, in case anything else pops up.

Cheers,

Andre

**Closed by akahles** 2022-02-11 20:46 UTC
