### ISSUE TITLE
IndexError in example_run.sh

### ISSUE THREAD

**Issue by kmhernan** [ratschlab/spladder#5] opened 2015-04-14 15:27 UTC
Hello,

I am receiving this error when trying to run the `example_run.sh`for the Python build. Any ideas??

```
Parsing annotation from examples/TAIR10_GFF3_genes.tiny.gff ...
... init structure
... done
Storing gene structure in examples/TAIR10_GFF3_genes.tiny.gff.pickle ...
... done
Augmenting splice graphs.
=========================
Generating splice graph ...

Total genes:							1
Total genes with alternative isoforms:				1
Total genes alternatively spliced:				1
Total constitutively spliced:					0
...done.

Loading introns from file ...
...done.

Testing for infeasible genes ...
found 0 unfeasible genes
...done.
Inserting cassette exons ...

... inserted 0 casette exons ....
... done.

Inserting intron retentions ...

... inserted 0 new intron retentions ...
...done.

Inserting new intron edges ...
... chr Chr1 - iteration 1/5

Traceback (most recent call last):
  File "spladder.py", line 219, in <module>
    spladder()
  File "spladder.py", line 175, in spladder
    spladder_core(CFG)
  File "/group/bioinformatics/software/SplAdder/041415/python/modules/core/spladdercore.py", line 26, in spladder_core
    genes = gen_graphs(genes, CFG)
  File "/group/bioinformatics/software/SplAdder/041415/python/modules/core/gen_graphs.py", line 156, in gen_graphs
    genes_mod, inserted_ = insert_intron_edges(tmp_genes, CFG)
  File "/group/bioinformatics/software/SplAdder/041415/python/modules/editgraph.py", line 732, in insert_intron_edges
    genes[rm_map == 1] = []
IndexError: too many indices for array
```

**Comment by akahles** [comment] 2015-04-14 16:19
Hi Kyle,
Which python version are you using and which scipy version? Are you computing on a mac or within a linux environment?

Thanks,

Andre

**Comment by kmhernan** [comment] 2015-04-14 16:22
Python 2.7.8
SciPy 0.15.1
GNU/Linux environment

**Comment by akahles** [comment] 2015-04-14 16:42
Thank you very much. I was able to reproduce your error and assume this is a package version issue. I will look into this and push an update as soon as I have resolved the problem.

**Comment by kmhernan** [comment] 2015-04-14 16:43
Excellent! Thanks.

**Comment by akahles** [comment] 2015-04-14 18:24
I believe that the problem lies on more rigorous checking in newer scipy versions. I have pushed an updated that fixed the problem for my instance. It would be great, if you could try the fix on your side.

**Comment by kmhernan** [comment] 2015-04-14 18:38
Thanks for the quick update. I just checked the update and it does run the example; however, it says that it failed.

Several warnings were printed:

```
/group/bioinformatics/software/SplAdder/041415/python/modules/reads.py:35: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  for read in infile.fetch(chr_name, start, stop, until_eof=True):

Inserting cassette exons ...
/group/bioinformatics/software/SplAdder/041415/python/modules/editgraph.py:843: RuntimeWarning: divide by zero encountered in double_scalars
  (sp.median(exon_cov[:min_len_pre]) / sp.median(pre_segment_cov[-min_len_pre:])) - 1 >= CFG['cassette_exon']['min_cassette_rel_diff']:
```

Then the last few lines of the output:

```
Reporting complete alt_5prime events:

No alt_5prime event could be confirmed. - Nothing to report.
confidence 3 / replicate 0

No mutex_exons event could be found. - Nothing to report
confidence 3 / replicate 0

No mult_exon_skip event could be found. - Nothing to report
examples/result_tiny/merge_graphs_alt_3prime_C3.pickle: FAILED
examples/result_tiny/merge_graphs_alt_5prime_C3.pickle: FAILED
examples/result_tiny/merge_graphs_exon_skip_C3.pickle: FAILED
md5sum: WARNING: 3 of 13 computed checksums did NOT match


TEST FAILED. - Please check your installation.
```

Please let me know what other information you need, or anything else you suggest!

**Comment by akahles** [comment] 2015-04-14 18:48
This looks like some pysam issue. Which pysam version are you using?

**Comment by kmhernan** [comment] 2015-04-14 18:50
0.7.5 it looks like

**Comment by akahles** [comment] 2015-04-14 18:51
Ok, thanks. I'll try to reproduce.

**Comment by akahles** [comment] 2015-04-14 20:43
Ok, I can reproduce the issue now. Seems to be a scipy/numpy version issue. Will look into it and post update here as soon as I have found the cause.

**Comment by akahles** [comment] 2015-04-14 21:17
I verified, that this version produces the expected result. Only one of the warnings had to do with a scipy version issue and has been fixed. Regarding the failing checksums, I realized that the representation of the custom objects depends on the environment and therefor can produce different checksums. I will change that and re-upload.

**Comment by kmhernan** [comment] 2015-04-14 22:19
Great! Let me know and I'll try again

**Comment by kmhernan** [comment] 2015-04-14 22:22
Oh! I just tried and ran fine. No problems!

**Comment by akahles** [comment] 2015-04-14 23:06
Great. Let me know, if you run into any further problems. I will close this issue for now but feel free to open re-open if necessary of create a new one.

**Closed by akahles** 2015-04-14 23:06 UTC
