### ISSUE TITLE
Run Error

### ISSUE THREAD

**Issue by akesarwani** [ratschlab/spladder#57] opened 2017-03-20 21:19 UTC
Hello, 
Below is the last few lines of error I am getting when I ran the job with a single BAM. I am using Gencode GFF3 and STAR mapped sorted BAM. Could you please help me out understanding the problem. 

RUN
 python spladder.py -b $bam -o $outdir -a $GFF -v y -t exon_skip,intron_retention,alt_3prime,alt_5prime,mutex_exons,mult_exon_skip -c 3 -p n #-e

OUTPUT
Number of XOR exons:						137

Make intron_retention events unique by strain
. . . events dropped: 0
Traceback (most recent call last):
  File "/home/kesara/tools/SplAdder/python/spladder.py", line 322, in <module>
    spladder()
  File "/home/kesara/tools/SplAdder/python/spladder.py", line 311, in spladder
    collect_events(CFG)
  File "/home/kesara/tools/SplAdder/python/modules/alt_splice/collect.py", line 371, in collect_events
    events_all = post_process_event_struct(intron_reten_pos_all, CFG)
  File "/home/kesara/tools/SplAdder/python/modules/alt_splice/events.py", line 62, in post_process_event_struct
    events = sort_events_by_event(events, CFG) 
  File "/home/kesara/tools/SplAdder/python/modules/alt_splice/events.py", line 27, in sort_events_by_event
    coord_list = sp.array([x.get_inner_coords() for x in event_list], dtype='double') 
ValueError: setting an array element with a sequence.

**Comment by benwbooth** [comment] 2017-06-01 22:01
looks to be a duplicate of #48

**Comment by akahles** [comment] 2019-04-30 09:31
Should have been resolved with #48. Please re-open if necessary.

**Closed by akahles** 2019-04-30 09:31 UTC
