### ISSUE TITLE
The iso1 and iso2 fields in the hdf5 files for all the event types except mutex are flipped

### ISSUE THREAD

**Issue by szkabel** [ratschlab/spladder#132] opened 2021-05-05 10:51 UTC
* spladder version: 2.4.3
* Python version: 3.6.9
* Operating System: Ubuntu 18.04.

### Description

The names of iso1 and iso2 fields in the hdf5 files for all event types except mutex exons are flipped compared against the read data at the genomic positions defined in the event_pos field or the gff3 file.
We tested the issue with the 1st sample file from the repo (i.e. Aligned.sortedByCoord.out.1.bam which we extracted to sam format with samtools). We have attached this sam file extended with colour highlights for the reads supporting each event described below (the annotations can be found in column R).

* **Alt3':** For event ID=alt_3prime.1 in gene8 in the gff3 file (merge_graphs_alt_3prime_C3.confirmed.gff3) iso1 is identified as the (5201,5300)-(5401,5500) exon sequence and iso2 as the (5201,5300)-(5351,5500) exon sequence. Checking the 1st sample's sam file we found 58 reads verifying iso1 (having the 5301-5400 edge), and 29 reads verifying iso2. However, in the corresponding hdf5 file (merge_graphs_alt_3prime_C3.counts.hdf5) we see these supports **flipped**: iso1[1,1]==29 and iso2[1,1]==58.

* **Alt5’:** For event ID=alt_5prime.1 in gene6 in the gff3 file (merge_graphs_alt_5prime_C3.confirmed.gff3) iso1 is identified as the (4051,4150)-(4251,4350) and iso2 as the (4051,4200)-(4251,4350). In the sam file there are 39 reads verifying iso1 (containing the edge 4151-4250) and 30 reads for iso2. In the corresponding hdf5 file (merge_graphs_alt_5prime_C3.counts.hdf5) the supports are **flipped** iso1[1,1]==37 and iso2[1,1]==39.

* **Exon skip:** For event ID=exon_skip.1 in gene1 in the gff3 file (merge_graphs_exon_skip_C3.confirmed.gff3) iso1 is identified as the 2-exon variant (i.e. exon skip), and iso2 as the 3-exon variant (exon retention). In the sam file there were 7 reads supporting iso1 (exon skip, edge 201-600) and 29 reads for iso2 (retained exon, edges 201-300 #support reads: 29 and 401-600 #support reads: 34, min is 29). In the corresponding hdf5 file (merge_graphs_exon_skip_C3.counts.hdf5) these supports are **flipped**: iso1[1,1]==29 and iso2[1,1]==7.

* **Multiple exon skip:** For event ID=mult_exon_skip.1, gene5 in the gff3 file (merge_graphs_mult_exon_skip_C3.confirmed.gff3) iso1 is the exon-skip and iso2 is the 4 exon variant. Based on the sam file and the support calculation for such exon skip [ (#of skipped exons + 1) * reads supporting the edge from the first to the last exon], the support for the exon skip (iso1) is = (2+1)*73 = 219. The support for iso2 is the sum of edges within it = 88+42=130. In the hdf5 file the corresponding counts are iso1[1,1]=130 and iso2[1,1] = 219 which is **flipped**.

* **Intron retention:** For event ID=intron_retention.1 in gene3 in the gff3 file (merge_graphs_intron_retention_C3.confirmed.gff3) iso1 is composed of 2 separate exons, while iso2 is the one with retained intron. In the sam file there are 47 reads supporting iso1 (reads with the edge 1401-1500) and 23 reads supporting iso2 (reads only within the retained intron). In the hdf5 file (merge_graphs_intron_retention_C3.counts.hdf5) iso1[1,1]==23 and iso2[1,1]==47. (**flipped**)

* **Mutex exons:** For event ID=mutex_exons.1, gene4 in the gff3 file (merge_graphs_mutex_exons_C3.confirmed.gff3) iso1 is identified as having the (2351,2450) exon and iso2 as having the exon (2551,2650). In the sam file there are 36 reads verifying iso1 and 95 reads verifying iso2. In this case this is matching with the hdf5 file’s variables iso1[1,1]==36 and iso2[1,1]==95.

We think this nomenclature is confusing between the output files and their clarification could enhance the understandability of your tool.
[Aligned.sortedByCoord.out.1_highlighted.sam.xlsx](https://github.com/ratschlab/spladder/files/6426535/Aligned.sortedByCoord.out.1_highlighted.sam.xlsx)

**Comment by akahles** [comment] 2021-05-11 16:40
Dear @szkabel ,

Thank you very much for this thorough report. This is indeed unintended behaviour. The general convention for naming the splice forms in SplAdder is that the form with fewer exon positions is termed iso1 and the form with more exon positions is termed iso2. Following this notion, the PSI would then be computed as (junctions for iso2 / (junctions for iso1 + junctions for iso2)). 
It turns out that for hdf5 count output this is consistently switched. It only worked for the mutex exons, because there an additional switch happened for the PSI computation (violating the above convention regarding the isoforms).

I have pushed a fix to the development branch, which I will make available with the next release.

Please let me know, in case you observe further discrepancies.

Best,

Andre

**Comment by akahles** [comment] 2022-01-05 17:03
This change is now available in the latest release.

**Closed by akahles** 2022-01-05 17:03 UTC
