### ISSUE TITLE
About AssertionError

### ISSUE THREAD

**Issue by wososa** [ratschlab/spladder#12] opened 2015-08-20 12:19 UTC
Hi,

I am running spladder. Below are the error messages...

```Number of XOR exons:                     1215

Make intron_retention events unique by strain
. . . . . . . . . . 10000
. . . . . . . . . . 20000
. . . events dropped: 17

Make intron_retention events unique by event
. . . . . . . . . . 10000
. . . . . . . . . . 20000
. . . events dropped: 18
saving intron retentions to testrun/merge_graphs_intron_retention_C3.pickle

Make exon_skip events unique by strain
. . . . . . . . . . 10000
. . . . . . . . . . 20000
. . . . events dropped: 33

Make exon_skip events unique by event
. . . . . . . . . . 10000
. . . . . . . . . . 20000
. . . . events dropped: 1100
saving exon skips to testrun/merge_graphs_exon_skip_C3.pickle

Make mult_exon_skip events unique by strain
. . . . . . events dropped: 6

Make mult_exon_skip events unique by event
. . . . . . events dropped: 613
saving multiple exon skips to testrun/merge_graphs_mult_exon_skip_C3.pickle

Make alt_5prime events unique by strain
. . . . . . . . . . 10000
.
Traceback (most recent call last):
  File "spladder.py", line 215, in <module>
    spladder()
  File "spladder.py", line 208, in spladder
    collect_events(CFG)
  File "/Users/admin/Documents/tools/spladder-master/python/modules/alt_splice/collect.py", line 414, in collect_events
    events_all = post_process_event_struct(alt_end_5prime_pos_all, CFG)
  File "/Users/admin/Documents/tools/spladder-master/python/modules/alt_splice/events.py", line 59, in post_process_event_struct
    events = make_unique_by_strain(events)
  File "/Users/admin/Documents/tools/spladder-master/python/modules/alt_splice/events.py", line 92, in make_unique_by_strain
    assert(event_list[i - 1].chr == event_list[i].chr)
AssertionError```

**Comment by akahles** [comment] 2015-08-20 17:21
Hi @woodydon, 
Thank you for reporting the bug. Would you mind sharing your annotation file with me? It looks like SplAdder is hitting some corner case here that I have not thought of and I would like to learn how the error occurs.

**Comment by woodydon** [comment] 2015-08-20 19:03
Sure, here are some of the lines in the annotation file (Homo_sapiens.GRCh37.75):

chr1    transcribed_unprocessed_pseudogene      gene    11869   14412   .       +       .       ID=ENSG00000223972;Name=DDX11L1
chr1    transcribed_unprocessed_pseudogene      mRNA    13661   14409   .       +       .       ID=ENST00000518655;Name=DDX11L1;Parent=ENSG00000223972
chr1    transcribed_unprocessed_pseudogene      exon    13661   14409   .       +       .       ID=ENST00000518655.4;Name=DDX11L1;Parent=ENST00000518655
chr1    transcribed_unprocessed_pseudogene      mRNA    13453   13670   .       +       .       ID=ENST00000450305;Name=DDX11L1;Parent=ENSG00000223972
chr1    transcribed_unprocessed_pseudogene      exon    13453   13670   .       +       .       ID=ENST00000450305.6;Name=DDX11L1;Parent=ENST00000450305
chr1    transcribed_unprocessed_pseudogene      mRNA    13403   13655   .       +       .       ID=ENST00000518655;Name=DDX11L1;Parent=ENSG00000223972
chr1    transcribed_unprocessed_pseudogene      exon    13403   13655   .       +       .       ID=ENST00000518655.3;Name=DDX11L1;Parent=ENST00000518655
chr1    transcribed_unprocessed_pseudogene      mRNA    13225   14412   .       +       .       ID=ENST00000515242;Name=DDX11L1;Parent=ENSG00000223972
chr1    transcribed_unprocessed_pseudogene      exon    13225   14412   .       +       .       ID=ENST00000515242.3;Name=DDX11L1;Parent=ENST00000515242
chr1    transcribed_unprocessed_pseudogene      mRNA    13221   13374   .       +       .       ID=ENST00000450305;Name=DDX11L1;Parent=ENSG00000223972
chr1    transcribed_unprocessed_pseudogene      exon    13221   13374   .       +       .       ID=ENST00000450305.5;Name=DDX11L1;Parent=ENST00000450305
chr1    processed_transcript    mRNA    13221   14409   .       +       .       ID=ENST00000456328;Name=DDX11L1;Parent=ENSG00000223972
chr1    processed_transcript    exon    13221   14409   .       +       .       ID=ENST00000456328.3;Name=DDX11L1;Parent=ENST00000456328
chr1    transcribed_unprocessed_pseudogene      mRNA    12613   13052   .       +       .       ID=ENST00000450305;Name=DDX11L1;Parent=ENSG00000223972
chr1    transcribed_unprocessed_pseudogene      exon    12613   12697   .       +       .       ID=ENST00000450305.3;Name=DDX11L1;Parent=ENST00000450305
chr1    transcribed_unprocessed_pseudogene      exon    12975   13052   .       +       .       ID=ENST00000450305.4;Name=DDX11L1;Parent=ENST00000450305
chr1    transcribed_unprocessed_pseudogene      mRNA    12613   12721   .       +       .       ID=ENST00000515242;Name=DDX11L1;Parent=ENSG00000223972
chr1    transcribed_unprocessed_pseudogene      exon    12613   12721   .       +       .       ID=ENST00000515242.2;Name=DDX11L1;Parent=ENST00000515242
chr1    processed_transcript    mRNA    12613   12721   .       +       .       ID=ENST00000456328;Name=DDX11L1;Parent=ENSG00000223972
chr1    processed_transcript    exon    12613   12721   .       +       .       ID=ENST00000456328.2;Name=DDX11L1;Parent=ENST00000456328
chr1    transcribed_unprocessed_pseudogene      mRNA    12595   12721   .       +       .       ID=ENST00000518655;Name=DDX11L1;Parent=ENSG00000223972
chr1    transcribed_unprocessed_pseudogene      exon    12595   12721   .       +       .       ID=ENST00000518655.2;Name=DDX11L1;Parent=ENST00000518655
chr1    transcribed_unprocessed_pseudogene      mRNA    12010   12227   .       +       .       ID=ENST00000450305;Name=DDX11L1;Parent=ENSG00000223972
chr1    transcribed_unprocessed_pseudogene      exon    12010   12057   .       +       .       ID=ENST00000450305.1;Name=DDX11L1;Parent=ENST00000450305
chr1    transcribed_unprocessed_pseudogene      exon    12179   12227   .       +       .       ID=ENST00000450305.2;Name=DDX11L1;Parent=ENST00000450305
chr1    transcribed_unprocessed_pseudogene      mRNA    11874   12227   .       +       .       ID=ENST00000518655;Name=DDX11L1;Parent=ENSG00000223972
chr1    transcribed_unprocessed_pseudogene      exon    11874   12227   .       +       .       ID=ENST00000518655.1;Name=DDX11L1;Parent=ENST00000518655
chr1    transcribed_unprocessed_pseudogene      mRNA    11872   12227   .       +       .       ID=ENST00000515242;Name=DDX11L1;Parent=ENSG00000223972
chr1    transcribed_unprocessed_pseudogene      exon    11872   12227   .       +       .       ID=ENST00000515242.1;Name=DDX11L1;Parent=ENST00000515242

**Comment by woodydon** [comment] 2015-08-20 19:08
I uploaded the first 2000 lines in the .gff file. Please change the .gif to .gff.


![tmp](https://cloud.githubusercontent.com/assets/7123929/9392932/3835603e-474d-11e5-8596-a194bb7f76b1.gif)

**Comment by woodydon** [comment] 2015-08-20 19:35
It will be great if you can make gtf as default. I know that gtf file has lots of formats, but you can at least accept the GTF file from Ensemble. It is where I download GTF files.

**Comment by akahles** [comment] 2015-08-20 19:39
Thanks for uploading the file. I will look at it shortly. Regarding the GTF request. SplAdder takes either GFF or GTF as input.

**Comment by woodydon** [comment] 2015-08-20 19:47
Thanks! I just noticed that GTF is also allowed. However, I got the errors...

Parsing annotation from Homo_sapiens.GRCh37.75.sorted.gtf ...
... init structure
Traceback (most recent call last):
  File "spladder.py", line 215, in <module>
    spladder()
  File "spladder.py", line 138, in spladder
    (genes, CFG) = init.init_genes_gtf(CFG['anno_fname'], CFG, CFG['anno_fname'] + '.pickle')
  File "/Users/admin/Documents/tools/spladder-master/python/modules/init.py", line 64, in init_genes_gtf
    genes[tags['gene_id']] = Gene(name=tags['gene_id'], start=start, stop=stop, chr=sl[0], strand=sl[6], source=sl[1], gene_type=tags['gene_type'])
KeyError: 'gene_type

**Comment by woodydon** [comment] 2015-08-20 19:49
GTF file.

#!genome-build GRCh37.p13
#!genome-version GRCh37
#!genome-date 2009-02
#!genome-build-accession NCBI:GCA_000001405.14
#!genebuild-last-updated 2013-09
1       pseudogene      gene    11869   14412   .       +       .       gene_id "ENSG00000223972"; gene_name "DDX11L1"; gene_source "ensembl_havana"; gene_biotype "pseudogene";
1       processed_transcript    transcript      11869   14409   .       +       .       gene_id "ENSG00000223972"; transcript_id "ENST00000456328"; gene_name "DDX11L1"; gene_source "ensembl_havana"; gene_biotype "pseudogene"; transcript_name "DDX11L1-002"; transcript_source "havana";
1       processed_transcript    exon    11869   12227   .       +       .       gene_id "ENSG00000223972"; transcript_id "ENST00000456328"; exon_number "1"; gene_name "DDX11L1"; gene_source "ensembl_havana"; gene_biotype "pseudogene"; transcript_name "DDX11L1-002"; transcript_source "havana"; exon_id "ENSE00002234944";
1       transcribed_unprocessed_pseudogene      transcript      11872   14412   .       +       .       gene_id "ENSG00000223972"; transcript_id "ENST00000515242"; gene_name "DDX11L1"; gene_source "ensembl_havana"; gene_biotype "pseudogene"; transcript_name "DDX11L1-201"; transcript_source "ensembl";
1       transcribed_unprocessed_pseudogene      exon    11872   12227   .       +       .       gene_id "ENSG00000223972"; transcript_id "ENST00000515242"; exon_number "1"; gene_name "DDX11L1"; gene_source "ensembl_havana"; gene_biotype "pseudogene"; transcript_name "DDX11L1-201"; transcript_source "ensembl"; exon_id "ENSE00002234632";
1       transcribed_unprocessed_pseudogene      transcript      11874   14409   .       +       .       gene_id "ENSG00000223972"; transcript_id "ENST00000518655"; gene_name "DDX11L1"; gene_source "ensembl_havana"; gene_biotype "pseudogene"; transcript_name "DDX11L1-202"; transcript_source "ensembl";
1       transcribed_unprocessed_pseudogene      exon    11874   12227   .       +       .       gene_id "ENSG00000223972"; transcript_id "ENST00000518655"; exon_number "1"; gene_name "DDX11L1"; gene_source "ensembl_havana"; gene_biotype "pseudogene"; transcript_name "DDX11L1-202"; transcript_source "ensembl"; exon_id "ENSE00002269724";
1       transcribed_unprocessed_pseudogene      transcript      12010   13670   .       +       .       gene_id "ENSG00000223972"; transcript_id "ENST00000450305"; gene_name "DDX11L1"; gene_source "ensembl_havana"; gene_biotype "pseudogene"; transcript_name "DDX11L1-001"; transcript_source "havana";

**Comment by akahles** [comment] 2015-08-20 19:49
Hm, I see. I'll make the gene_type optional. It is currently not used, anyway.

**Comment by woodydon** [comment] 2015-08-20 19:52
Looking forward to download the updated version!

**Comment by akahles** [comment] 2015-08-24 16:43
I have updated SplAdder to no longer require the gene_type field. Could you re-try and see if GTF parsing works for you now? 

Unfortunately, I was not able to reproduce the error above with the GFF file you sent me. I could try again with the full GFF file, if you are willing to send it to me.

**Comment by jotrema** [comment] 2015-09-28 19:23
I just got this error. I utilized GRCh38.80.gtf 

Traceback (most recent call last):
  File "spladder.py", line 255, in <module>
    spladder()
  File "spladder.py", line 248, in spladder
    collect_events(CFG)
  File "/home/joel/data/softwares/spladder-master/python/modules/alt_splice/collect.py", line 435, in collect_events
    events_all = post_process_event_struct(alt_end_3prime_pos_all, CFG)
  File "/home/joel/data/softwares/spladder-master/python/modules/alt_splice/events.py", line 59, in post_process_event_struct
    events = make_unique_by_strain(events)
  File "/home/joel/data/softwares/spladder-master/python/modules/alt_splice/events.py", line 96, in make_unique_by_strain
    assert(event_list[i - 1].gene_name != event_list[i].gene_name)
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

I hope this helps !

J.

**Comment by akahles** [comment] 2018-06-19 14:52
This should be fixed, please re-open if still relevant.

**Closed by akahles** 2018-06-19 14:52 UTC
