### ISSUE TITLE
KeyError: 'NM'

### ISSUE THREAD

**Issue by nicolasstransky** [ratschlab/spladder#24] opened 2016-02-16 21:57 UTC
Hi there,
I'm fairly new to spladder and was trying to use it on some data of mine but ran into an error. The example data runs fine but when I use spladder on my data I get this:

```
python /tmp/spladder/python/spladder.py -a gencode.v23.annotation.gff3 -b sample1_Aligned.bam,sample2_Aligned.bam -o test
Augmenting splice graphs.
=========================
Generating splice graph ...
...done.

Loading introns from file ...
Traceback (most recent call last):
  File "/tmp/spladder/python/spladder.py", line 265, in <module>
    spladder()
  File "/tmp/spladder/python/spladder.py", line 184, in spladder
    spladder_core(CFG)
  File "/tmp/spladder/python/modules/core/spladdercore.py", line 21, in spladder_core
    genes = gen_graphs(genes, CFG)
  File "/tmp/spladder/python/modules/core/gen_graphs.py", line 83, in gen_graphs
    introns = get_intron_list(genes, CFG)
  File "/tmp/spladder/python/modules/reads.py", line 371, in get_intron_list
    intron_list_tmp = add_reads_from_bam(gg, CFG['bam_fnames'], ['intron_list'], CFG['read_filter'], CFG['var_aware'], CFG['primary_only'], CFG['ignore_mismatch_tag'])
  File "/tmp/spladder/python/modules/reads.py", line 152, in add_reads_from_bam
    (introns, spliced_coverage) = get_all_data(blocks[b], filenames, mapped=False, filter=filter, var_aware=var_aware, primary_only=primary_only, no_mm=no_mm)
  File "/tmp/spladder/python/modules/reads.py", line 265, in get_all_data
    (coverage_tmp, introns_tmp) = get_reads(fname, contig_name, block.start, block.stop, strand, filter, mapped, spliced, var_aware, collapse, primary_only, no_mm)
  File "/tmp/spladder/python/modules/reads.py", line 42, in get_reads
    if filter_read(read, filter, spliced, mapped, strand, primary_only, var_aware, no_mm):
  File "/tmp/spladder/python/modules/reads.py", line 411, in filter_read
    return filter['mismatch'] < tags['NM']
KeyError: 'NM'
```

Any idea?
Thanks

**Comment by akahles** [comment] 2016-02-16 22:02
Hi Nicolas,

Thank you for trying out SplAdder. The software performs filtering on the input reads to only retain confident alignments, this is done using the SAM tag NM:i:<mismatch>

Anyway, if your file does not have this flag set, then you can run SplAdder with the additional command line option --ignore_mismatches=n to switch of the NM filter.

Best,

Andre

**Comment by nicolasstransky** [comment] 2016-02-17 00:17
Hi Andre,
The files generated by STAR have this tag set: nM:i:<mismatch>. Admittedly this does not comply to the SAM specifications...
In any case, thanks for the advice. It turns out that the command that works is `--ignore_mismatches=y`.
Nico

**Comment by akahles** [comment] 2016-02-17 00:20
Hi Nico,

The nM:i: tag produced by STAR has a slightly different meaning. This will give the edit operations per fragment. The normal NM:i: will give the edit operations per mate. You can get STAR to output the NM:i: tag using the option "outSAMattributes”.

Cheers,

Andre

**Comment by nicolasstransky** [comment] 2016-02-17 15:34
OK thanks!

I am however hitting another error, much further in the process:

```
...
Store genes at: test/spladder/genes_graph_conf3.merge_graphs.pickle

1/2
genes: 60498
sample 1/1
...................................................50
...
..................................................17850
................................................Traceback (most recent call last):
  File "/tmp/spladder/python/spladder.py", line 265, in <module>
    spladder()
  File "/tmp/spladder/python/spladder.py", line 249, in spladder
    count_graph_coverage_wrapper(fn_in_count, fn_out_count, CFG)
  File "/tmp/spladder/python/modules/count.py", line 148, in count_graph_coverage_wrapper
    counts_tmp = count_graph_coverage(genes, CFG['bam_fnames'][s_idx], CFG)
  File "/tmp/spladder/python/modules/count.py", line 85, in count_graph_coverage
    (tracks, intron_list) = add_reads_from_bam(gg, fn_bam[f], ['exon_track','intron_list'], None, CFG['var_aware'], CFG['primary_only']);
  File "/tmp/spladder/python/modules/reads.py", line 140, in add_reads_from_bam
    (introns, coverage) = get_all_data(blocks[b], filenames, filter=filter, var_aware=var_aware, primary_only=primary_only, no_mm=no_mm)
  File "/tmp/spladder/python/modules/reads.py", line 265, in get_all_data
    (coverage_tmp, introns_tmp) = get_reads(fname, contig_name, block.start, block.stop, strand, filter, mapped, spliced, var_aware, collapse, primary_only, no_mm)
  File "/tmp/spladder/python/modules/reads.py", line 39, in get_reads
    for read in infile.fetch(chr_name, start, stop, until_eof=True):
  File "pysam/calignmentfile.pyx", line 727, in pysam.calignmentfile.AlignmentFile.fetch (pysam/calignmentfile.c:9892)
  File "pysam/calignmentfile.pyx", line 647, in pysam.calignmentfile.AlignmentFile._parseRegion (pysam/calignmentfile.c:8980)
ValueError: start out of range (-73)
```

**Comment by akahles** [comment] 2016-02-17 16:11
This looks like your alignment file having negative start positions. This is not conform to the SAM standard. Could you please check whether this is the case?

Cheers,

Andre

**Comment by nicolasstransky** [comment] 2016-02-17 18:31
hi Andre,
Thanks for this suggestion: I have checked all files and it doesn't appear like there are negative start positions. I used the following command: `samtools view sample.bam | awk -F '\t' '$4<0 {print $0}'` and it didn't return anything.
Nico

**Comment by akahles** [comment] 2016-02-17 18:51
Hi Nico,

To what kind of organism are you working on? Would it be possible/allowed to share a small setup with me so I could reproduce the error?

Thanks and Cheers,

Andre

**Comment by nicolasstransky** [comment] 2016-02-17 18:56
These are files aligned on the Human hg38 genome / Gencode v23 transcriptome using STAR. I have attached the bam file header so you can check.
Unfortunately, due to the data access conditions for these data, I cannot share them with you, but if you have ideas on how to isolate the problematic reads I can try to extract those.
Nico

[header.txt](https://github.com/ratschlab/spladder/files/134972/header.txt)

**Comment by akahles** [comment] 2016-02-21 20:17
Thanks for the header. I will try to reproduce with one of the human RNA-Seq files available to me.

**Comment by abaten** [comment] 2016-04-05 23:21
Dear Andre,

Is there any update on this issue?
It seems I have the exact error as well.
`..................................................39500
.........................................Traceback (most recent call last):
  File "/software/Alternative_Splcing/spladder/python/spladder.py", line 265, in <module>
    spladder()
  File "/software/Alternative_Splcing/spladder/python/spladder.py", line 249, in spladder
    count_graph_coverage_wrapper(fn_in_count, fn_out_count, CFG)
  File "/software/Alternative_Splcing/spladder/python/modules/count.py", line 148, in count_graph_coverage_wrapper
    counts_tmp = count_graph_coverage(genes, CFG['bam_fnames'][s_idx], CFG)
  File "/software/Alternative_Splcing/spladder/python/modules/count.py", line 85, in count_graph_coverage
    (tracks, intron_list) = add_reads_from_bam(gg, fn_bam[f], ['exon_track','intron_list'], None, CFG['var_aware'], CFG['primary_only']);
  File "/software/Alternative_Splcing/spladder/python/modules/reads.py", line 140, in add_reads_from_bam
    (introns, coverage) = get_all_data(blocks[b], filenames, filter=filter, var_aware=var_aware, primary_only=primary_only, no_mm=no_mm) 
  File "/software/Alternative_Splcing/spladder/python/modules/reads.py", line 265, in get_all_data
    (coverage_tmp, introns_tmp) = get_reads(fname, contig_name, block.start, block.stop, strand, filter, mapped, spliced, var_aware, collapse, primary_only, no_mm)
  File "/software/Alternative_Splcing/spladder/python/modules/reads.py", line 39, in get_reads
    for read in infile.fetch(chr_name, start, stop, until_eof=True):
  File "pysam/calignmentfile.pyx", line 860, in pysam.calignmentfile.AlignmentFile.fetch (pysam/calignmentfile.c:10789)
  File "pysam/calignmentfile.pyx", line 788, in pysam.calignmentfile.AlignmentFile.parse_region (pysam/calignmentfile.c:10349)
ValueError: start out of range (-161)
`

I am happy to share my bam files.

Regards.

**Comment by akahles** [comment] 2016-04-07 14:40
I was not able to reproduce the problem yet. If you could share your bam file, that would be highly appreciated.

**Comment by akahles** [comment] 2016-04-08 21:40
Dear Abdul,

Thank you very much for sending the data. I can reproduce the issue now and will try to resolve it as soon as possible.

**Comment by akahles** [comment] 2016-04-12 17:56
Hi Abdul and Nico,

Thank  you for sending me data to reproduce this. I pushed a fix to the development branch that hopefully resolves the problem. I also added some more prefiltering steps to annotation parsing, to remove some cases where annotated genes overlap. I can handle this better in case of strand-specific alignment data, but for now I just filter out overlapping annotations.

I will close this issue for now. In case the above problem should not be resolved, please re-open. If you spot other errors, please report as a new issue - this makes it easier for me to track.

Thanks and Cheers,
Andre

**Closed by akahles** 2016-04-12 17:56 UTC

**Comment by jfass** [comment] 2019-04-02 21:49
So, I've got STAR alignments that include the "nM:i" tag (not the standard "NM:i"). I see from the discussion above that I could rerun STAR with a flag to force output of NM (mismatches per read) instead of nM (mismatches per fragment). But I could also use the --ignore-mismatches=y option to spladder. So my question is, should any of these options have any significant impact on mapping novel splice junctions? I would *guess* not, but it'd be nice to have an expert opinion on this.

Thanks,
~Joe

**Comment by akahles** [comment] 2019-04-03 21:16
Hi Joe,
Thanks for looking into SplAdder. The `--ignore-mismatches` option should only be used as a last resort, as this switches off the filtering of read alignments by edit operations and will increase the noise in your data quite a bit (depending on the quality of your reads). So from the two options you mention, I would suggest to re-run STAR with the NM tag. 
However, in the latest release I just pushed, I added a new command line option `--set-mm-tag`, where you can specify the mismatch tag to be used. So you could just run SplAdder with `--set-mm-tag nM`.
Cheers,
Andre

**Comment by jfass** [comment] 2019-04-04 00:04
Thanks Andre! So ... does setting '--set-mm-tag nM' make SplAdder aware that it's looking at per-fragment mismatches, not per-read mismatches? Or, is it critical if it doesn't?

So you have no obligation to answer this, but if I've installed spladder via pip in a python3 venv, is there a way to pull in a github commit?? or should I just install from source from github separately?

~Joe

**Comment by akahles** [comment] 2019-04-04 06:22
> Thanks Andre! So ... does setting '--set-mm-tag nM' make SplAdder aware that it's looking at per-fragment mismatches, not per-read mismatches? Or, is it critical if it doesn't?

SplAdder will just read the `nM` tag `NM` tag. To be interpreted correctly, you could set the `--readlength` to the length of the read pair, then the edit distance thresholds are computed relative to the pair's length (which would correspond to the fragment length in STAR).

> So you have no obligation to answer this, but if I've installed spladder via pip in a python3 venv, is there a way to pull in a github commit?? or should I just install from source from github separately?

I have released the latest version (2.1.0) also to pypi. You can just do `pip install spladder --upgrade` and should get the latest changes.

**Comment by jfass** [comment] 2019-05-13 20:02
Many thanks; spladder 2.2.1 has been working for me. I have a more scienc-y issue which I'll submit a new issue for.
~JOe

**Comment by gvcaldas** [comment] 2022-03-16 21:14
Hi Andre,
I am trying to run spladder and I ran into the same issue of the nM tag as discussed here. I ran all my alignments (which are too many) w/o the outSAMattributes option because at the time I did not decide which packages I wanted to try for alternative splicing analysis. I really don't want to repeat the whole STAR alignment since it was two manual passes and many samples. I am trying to the --set-mm-tag nM that you suggest, but I am not clear about how to set the --readlength that you mentioned in the comment above. My read pair size is 300. I thought you meant including the parameter --readlength 300 in the command for spladder, but I get an error that this is an unrecognized argument. Could you please guide me into how to set the read pair length to 300? thanks!
Gina

**Comment by erzakiev** [comment] 2023-03-14 10:41
Hello, I join the last person in the fact that yes indeed the argument `--readlength 150` isn't recognized. Where to edit this parameter, in which config file..?
